### PR TITLE
prepare for model verification

### PR DESCRIPTION
**Pull request by bqpd**
for convexengineering/gpkit#1238

### CODE REVIEW

**Comment by bqpd** [comment]
@mayork or @1ozturkbe, could you review this?

**Comment by mayork** [comment]
@bqpd out of curiosity what is "verification"

**Comment by bqpd** [comment]
heh, every time an instance of a named model is created we will check to make sure that it's appropriately bounded. With this it should be possible to guarantee dual feasibility and modularity before solving.

**Comment by mayork** [comment]
@bqpd oh awesome! are we skipping that step for everything in this repo?

**Comment by mayork** [comment]
just not sure what the skip verification means

**Comment by bqpd** [comment]
yup yup. It should be doable to integrate signomials / sigeqs but I haven't tried to write that algorithm yet :p

**Comment by bqpd** [comment]
I'd love to piece-by-piece integrate these models into that framework, though! I think it's really going to be a good change to the way gpkit model development works.

**Comment by mayork** [comment]
@bqpd yeah this sounds like a great feature! I'm reviewing paper proofs right now but when I'm done with that (hopefully tomorrow night) I'll take a look at these

**Pull request merged**
